services:
  gemini:
    image: git.joeac.net/joeac/joeac.net-gemini
    container_name: joeac.net-gemini
    build:
      context: .
      dockerfile: gemini.Dockerfile
    ports:
      - "1965:1965"

  http:
    image: git.joeac.net/joeac/joeac.net-http
    container_name: joeac.net-http
    build:
      context: .
      dockerfile: http.Dockerfile
    env_file:
      - .env
    ports:
      - "8080:80"

  smtp:
    image: git.joeac.net/joeac/joeac.net-smtp
    container_name: joeac.net-smtp
    build:
      context: .
      dockerfile: smtp.Dockerfile
      args:
        SMTP_PORT: 2500
    env_file:
      - .env
    environment:
      SMTP_PORT: 2500
      SMTP_USER: smtp
      SMTP_PASSWORD: smtp
      REMOTE_SMTP_PASSWORD_FILE: /run/secrets/remote_smtp_password
    secrets:
      - remote_smtp_password

  vaultwarden:
    image: docker.io/vaultwarden/server:latest
    container_name: joeac.net-vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://pwd.joeac.net"
    volumes:
      - ./vaultwarden/vw-data/:/data/
    ports:
      - "9000:80"

secrets:
  remote_smtp_password:
    external: true
