services:
  capsule:
    build:
      context: capsule
    ports:
      - "1965:1965"

  website:
    build:
      context: website
      args:
        LOCAL_SMTP_HOST: smtp
        LOCAL_SMTP_PORT: 2500
        LOCAL_SMTP_PASSWORD: smtp
    env_file:
      - .env
    ports:
      - "8000:4321"

  smtp:
    build:
      context: smtp
      args:
        LOCAL_SMTP_PORT: 2500
    env_file:
      - .env
    environment:
      LOCAL_SMTP_PORT: 2500
      LOCAL_SMTP_PASSWORD: smtp
      REMOTE_SMTP_PASSWORD_FILE: /run/secrets/remote_smtp_password
    secrets:
      - remote_smtp_password

secrets:
  remote_smtp_password:
    external: true
