FROM git.joeac.net/joeac/armv7/msmtp:1.8.32-alpine3.23
ARG LOCAL_SMTP_PORT
EXPOSE $LOCAL_SMTP_PORT
ENV SMTP_PORT=${LOCAL_SMTP_PORT} \
  SMTP_USER=${LOCAL_SMTP_USER} \
  SMTP_PASSWORD=${LOCAL_SMTP_PASSWORD}
COPY smtp/.msmtprc ./
