server {
    server_name ln.joeac.net;

    location / {
        root /var/ln.joeac.net/public;
        try_files $uri $uri.html $uri/index.html =404;
        error_page 404 /index.html;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/ln.joeac.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ln.joeac.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = ln.joeac.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name ln.joeac.net;
    listen 80;
    return 404; # managed by Certbot
}
