Domains:
	mail.joeac.net:
		ClientSettingsDomain: clientsettings.mail.joeac.net
		LocalpartCatchallSeparator: +
		DKIM:
			Selectors:
				2026a:
					Expiration: 72h
					PrivateKeyFile: dkim/2026a._domainkey.mail.joeac.net.20260705T163220.rsa2048.privatekey.pkcs8.pem
				2026b:
					Expiration: 72h
					PrivateKeyFile: dkim/2026b._domainkey.mail.joeac.net.20260705T163220.rsa2048.privatekey.pkcs8.pem
			Sign:
				- 2026a
		DMARC:
			Localpart: dmarcreports
			Account: me
			Mailbox: DMARC
		MTASTS:
			PolicyID: 20260705T153220
			Mode: enforce
			MaxAge: 24h0m0s
			MX:
				- mail.joeac.net
		TLSRPT:
			Localpart: tlsreports
			Account: me
			Mailbox: TLSRPT
Accounts:
	me:
		Domain: mail.joeac.net
		Destinations:
			me@mail.joeac.net: nil
		SubjectPass:
			Period: 12h0m0s
		RejectsMailbox: Rejects
		AutomaticJunkFlags:
			Enabled: true
			JunkMailboxRegexp: ^(junk|spam)
			NeutralMailboxRegexp: ^(inbox|neutral|postmaster|dmarc|tlsrpt|rejects)
		JunkFilter:
			Threshold: 0.950000
			Params:
				Onegrams: true
				MaxPower: 0.010000
				TopWords: 10
				IgnoreWords: 0.100000
				RareWords: 2
		NoCustomPassword: true
MonitorDNSBLs:
	- sbl.spamhaus.org
	- bl.spamcop.net
