DataDir: ../data
LogLevel: debug
User: mox
Hostname: mail.joeac.net
AdminPasswordFile: adminpasswd
Listeners:
	internal:
		IPs:
			- 127.0.0.1
			- ::1
		Hostname: localhost
		AccountHTTP:
			Enabled: true
			Port: 1080
			Forwarded: true
		AdminHTTP:
			Enabled: true
			Port: 1080
			Forwarded: true
		WebmailHTTP:
			Enabled: true
			Port: 1080
			Forwarded: true
		WebAPIHTTP:
			Enabled: true
			Port: 1080
			Forwarded: true
		MetricsHTTP:
			Enabled: true
		AutoconfigHTTPS:
			Enabled: true
			Port: 81
			NonTLS: true
		MTASTSHTTPS:
			Enabled: true
			Port: 81
			NonTLS: true
		WebserverHTTP:
			Enabled: true
			Port: 81
	public:
		IPs:
			- 192.168.178.75
			- fdc9:6aec:7a18:0:2e0:4cff:fe61:9b17
		NATIPs:
			- 217.155.190.42
			- fdc9:6aec:7a18:0:2e0:4cff:fe61:9b17
		TLS:
			KeyCerts:
				-
					CertFile: /etc/letsencrypt/live/mail.joeac.net/fullchain.pem
					KeyFile: /etc/letsencrypt/live/mail.joeac.net/privkey.pem
				-
					CertFile: /etc/letsencrypt/live/mta-sts.mail.joeac.net/fullchain.pem
					KeyFile: /etc/letsencrypt/live/mta-sts.mail.joeac.net/privkey.pem
				-
					CertFile: /etc/letsencrypt/live/autoconfig.mail.joeac.net/fullchain.pem
					KeyFile: /etc/letsencrypt/live/autoconfig.mail.joeac.net/privkey.pem
				-
					CertFile: /etc/letsencrypt/live/clientsettings.mail.joeac.net/fullchain.pem
					KeyFile: /etc/letsencrypt/live/clientsettings.mail.joeac.net/privkey.pem
		SMTP:
			Enabled: true
		Submissions:
			Enabled: true
		IMAPS:
			Enabled: true
Postmaster:
	Account: me
	Mailbox: Postmaster
HostTLSRPT:
	Account: me
	Mailbox: TLSRPT
	Localpart: tlsreports
